name: Build semgrep container
description: GitHub Action that builds semgrep container using returntocorp/semgrep image and passses semgrep command as args
inputs:
  semgrep-app-token:
    required: true
    description: SemGrep API token to be added to repo that allows to pull latest rule config from ruleboard in Semgrep UI
runs:
  using: composite
  env:
   SEMGREP_APP_TOKEN: ${{ inputs.semgrep-app-token }}
  container:
      image: returntocorp/semgrep
      options: --user semgrep
    steps:
      - uses: actions/checkout@v2
      - name: Run Semgrep
        run: semgrep ci
