# Name of this GitHub Actions workflow.
name: Static code analysis using Semgrep

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
  # [optional] Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: "20 17 * * *" # Sets Semgrep to scan every day at 17:20 UTC.
    # It is recommended to change the schedule to a random time.

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: Semgrep
    runs-on: ubuntu-20.04
    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3
      - uses: JasonTestOrgSemgrepMK2/test-actions/test-dir/semgrep@v1
        with:
          semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
